services:
  auth-service:
    build: ./auth-service
    ports:
      - "4005:4005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO:update
      - SPRING_SQL_INIT_MODE:always
    depends_on:
      - auth-service-db
    networks:
      - internal

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "4004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway-1
      - api-gateway-2
      - api-gateway-3
    networks:
      - internal
    restart: always

  api-gateway-1:
    build: ./api-gateway
    ports:
      - "4101:4004"
    depends_on:
      - auth-service
      - goal-service
    networks:
      - internal

  api-gateway-2:
    build: ./api-gateway
    ports:
      - "4102:4004"
    depends_on:
      - auth-service
      - goal-service
    networks:
      - internal

  api-gateway-3:
    build: ./api-gateway
    ports:
      - "4103:4004"
    depends_on:
      - auth-service
      - goal-service
    networks:
      - internal

  goal-service:
    build: ./goal-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://goal-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - goal-service-db
    networks:
      - internal

  goal-service-db:
    image: postgres:latest
    container_name: goal-service-db
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    networks:
      - internal

networks:
  internal:
    driver: bridge
