openapi: 3.0.3
info:
  title: Goal Categories API
  version: 1.0.0
  description: API for managing thematic categories for goals.

paths:
  /categories:
    post:
      summary: Admin creates thematic categories for goals
      security:
        - bearerAuth: []
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreateDto'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'
        '401':
          description: Unauthorized - User not logged in or not admin
        '403':
          description: Forbidden - User lacks admin rights

    get:
      summary: Allows users to get current categories
      security:
        - bearerAuth: []
      tags:
        - Categories
      parameters:
        - name: sort
          in: query
          description: Sort categories by field name
          required: false
          schema:
            type: string
            example: name
        - name: direction
          in: query
          description: Sort direction
          required: false
          schema:
            type: string
            enum: [ASC, DESC]
            example: ASC
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'
        '401':
          description: Unauthorized - User not logged in
        '403':
          description: Forbidden - User role not allowed (ADMIN, MODERATOR, USER allowed)

  /categories/{category_id}:
    delete:
      summary: Admin deletes category
      security:
        - bearerAuth: []
      tags:
        - Categories
      parameters:
        - name: category_id
          in: path
          description: ID of the category to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Category deleted successfully
        '401':
          description: Unauthorized - User not logged in or not admin
        '403':
          description: Forbidden - User lacks admin rights
        '404':
          description: Category not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CategoryCreateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the category
          example: "Health & Fitness"
        description:
          type: string
          description: Optional description of the category
          example: "Goals related to physical and mental health"

    CategoryDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Health & Fitness"
        description:
          type: string
          example: "Goals related to physical and mental health"